homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret homeassistant_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml
  packages: !include_dir_named packages

#enable logging
#logger: 
#  default: critical
#  logs:
#    homeassistant.components.light: debug
#    homeassistant.components.light.template: debug
#    homeassistant.core: debug

#recorder:
#  purge_days: 3
#  exclude:
#    entities:
#      - sun.sun
#      - sensor.floorplan_song
#      - sensor.floorplan_artist
#      - sensor.dark*
#      - sensor.floorplan_date
#      - sensor.floorplan_time

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_api_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url
  #server_port: 443

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret

ecobee:
  api_key: !secret ecobee_api_key

group: !include_dir_merge_named includes/group
automation: !include_dir_merge_list includes/automation
script: !include_dir_merge_named includes/script
scene: !include_dir_merge_list includes/scene
sensor: !include_dir_merge_list includes/sensor
shell_command: !include_dir_merge_named includes/shell_command
switch: !include_dir_merge_list includes/switch
cover:
plant: !include_dir_merge_named includes/plant

panel_custom: 
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

media_player:
  - platform: spotify
    client_id: !secret media_player_spotify_client_id
    client_secret: !secret media_player_spotify_client_secret

ios:

lutron_caseta:
  host: !secret lutron_caseta_host

emulated_hue:
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
    - switch

#zwave:
#  usb_path: /dev/zwave

zha:
  usb_path: /dev/zigbee
  database_path: /home/homeassistant/.homeassistant/zigbee.db

remote:
  - platform: harmony
    name: Living Room TV
    host: !secret remote_harmony_host

input_select:
  living_room_tv:
    name: Living Room TV
    options:
      - Powered Off
      - Watch TV
      - Watch Apple TV
      - Watch Fire TV
      - Listen to Music
      - Play PS3
      - Play Wii
      - Watch DLNA
    initial: Powered Off
    icon: mdi:monitor
