alias: 'Turn on balcony lights at sunset'
  trigger:
    platform: sun
    event: sunset
    offset: "00:00:00"
  action:
    service: light.turn_on
    entity_id: light.balcony
    data:
      brightness: 255
      transition: 300

alias: 'Turn balcony lights to 50% at 11'
  trigger:
    platform: time
    at: "23:00:00"
  action:
    service: light.turn_on
    entity_id: light.balcony
    data:
      brightness: 128
      transition: 300

alias: 'Turn off balcony lights at 1'
  trigger:
    platform: time
    at: "01:00:00"
  action:
    service: light.turn_off
    entity_id: light.balcony
    data:
      transition: 300 

alias: 'Monitor last action'
  trigger:
    platform: state
    entity_id:
      - light.balcony
      - light.bathroom_overhead
      - light.bullet
      - light.zha_fe0299fd_10
      - light.chris
      - light.closet
      - light.couch
      - light.den_overhead
      - light.floor
      - light.zha_fe0299d3_10
      - light.guest_bathroom_overhead
      - light.guest_bathroom_shower
      - light.hallway_light
      - light.kevins
      - light.office_lamp
      - light.pendant
      - light.shower
      - light.tv
      - light.under_cabinet
      - switch.bathroom_fan
      - switch.entry
      - switch.guest_bathroom_fan
      - switch.kitchen_overhead
      - switch.laundry
      - switch.office_fan
  action:
    - service: shell_command.save_state
      data_template:
        value: "echo {{trigger.to_state.attributes.friendly_name}} changed to {{trigger.to_state.state}} at {{now().strftime('%l:%M%p %Z on %b %d, %Y')}}"

alias: 'Away to home mode'
  trigger:
    platform: state
    entity_id: group.everything
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.home_mode
        state: Away
  action:
    - service: shell_command.save_mode
      data_template:
        value: "echo Home"
    - service: media_player.media_pause
      data:
        entity_id: media_player.spotify
