- platform: template
  switches:
    living_room_left_cover:
      value_template: "{{ is_state_attr('cover.living_room_left', 'current_position', 100) }}"
      turn_on:
        service: cover.open_cover
        entity_id: cover.living_room_left
      turn_off:
        service: cover.close_cover
        entity_id: cover.living_room_left
    living_room_middle_cover:
      value_template: "{{ is_state_attr('cover.living_room_middle', 'current_position', 100) }}"
      turn_on:
        service: cover.open_cover
        entity_id: cover.living_room_middle
      turn_off:
        service: cover.close_cover
        entity_id: cover.living_room_middle
    living_room_right_cover:
      value_template: "{{ is_state_attr('cover.living_room_right', 'current_position', 100) }}"
      turn_on:
        service: cover.open_cover
        entity_id: cover.living_room_right
      turn_off:
        service: cover.close_cover
        entity_id: cover.living_room_right
    bedroom_cover:
      value_template: "{{ is_state_attr('cover.bedroom', 'current_position', 100) }}"
      turn_on:
        service: cover.open_cover
        entity_id: cover.bedroom
      turn_off:
        service: cover.close_cover
        entity_id: cover.bedroom
